from tkinter import *
from tkinter import ttk
obj=Tk()
obj.geometry('800x800')
obj.title('run')
obj.config(bg='blue')
#img=Image.open ('https://thewowstyle.com/wp-content/uploads/2015/01/nature-images..jpg')
#bg=PhotoImage(file='logo.jpg')
#mylabel=Label(obj,image=bg)
#mylabel.pack()
#photo=PhotoImage(obj,file="https://thewowstyle.com/wp-content/uploads/2015/01/nature-images..jpg")
#photo.pack()
obj=Tk()
obj.geometry('800x800')
obj.title('run')
obj.config(bg='blue')
def new():
    w=Toplevel(obj)
    w.geometry('250x250')
    w.title('newwindow')
    lblnew=Label(w,text='firstname',font=('times',18,'bold'))
    lblnew.pack()
    
m=Menu(obj)
f=Menu(m,tearoff=0)
f.add_command(label='new',command=new)
f.add_command(label='open')
f.add_separator()
f.add_command(label='close')
f.add_separator()
f.add_command(label='save as')
f.add_separator()
f.add_command(label='exit',command=obj.destroy)
m.add_cascade(label='file',menu=f)


a=Menu(m,tearoff=0)
a.add_command(label='view')
a.add_separator()
a.add_command(label='full view')
a.add_separator()
a.add_command(label='maximize')
a.add_checkbutton(label='minimize')
a.add_separator()
a.add_radiobutton(label='allow')
m.add_cascade(label='display',menu=a)

obj.config(menu=m)
obj.mainloop()